[package]
name = "pydocx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docx-rs = "0.3.4"
pyo3 = "0.16.2"

[features]
